#pragma once

void initializeData();
void displayMenu();
void listStudents(); 
void listCourses();
void listteachers();
void listrecords();
void queryStudent();
void addStudent();
void queryCourse();
void queryTeacher();
void queryRecord();
void deleteStudent();
void deleteStudent();
void updateStudent();
void deleteTeacher();
void deleteCourse();
void queryRecord();
void deleteRecord();
void updateTeacher();
void updateCourse();
void addTeacher();
void addCourse();
void addRecord();
